//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTP3BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTP3ESHEntities : DbContext
    {
        public RTP3ESHEntities()
            : base("name=RTP3ESHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RTP3_AOEnergo> RTP3_AOEnergo { get; set; }
        public virtual DbSet<RTP3_BD> RTP3_BD { get; set; }
        public virtual DbSet<RTP3_Centers> RTP3_Centers { get; set; }
        public virtual DbSet<RTP3_Coors> RTP3_Coors { get; set; }
        public virtual DbSet<RTP3_GUID> RTP3_GUID { get; set; }
        public virtual DbSet<RTP3_PES> RTP3_PES { get; set; }
        public virtual DbSet<RTP3_Regions> RTP3_Regions { get; set; }
        public virtual DbSet<RTP3_RES> RTP3_RES { get; set; }
        public virtual DbSet<RTP3_Sections> RTP3_Sections { get; set; }
        public virtual DbSet<RTP3_Unom> RTP3_Unom { get; set; }
    }
}
