//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTP3BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTP3_Sections
    {
        public string Name { get; set; }
        public int GUID { get; set; }
        public int OwnerGUID { get; set; }
        public decimal Unom { get; set; }
        public Nullable<decimal> Rc { get; set; }
        public Nullable<decimal> Xc { get; set; }
        public System.Guid ID_BD { get; set; }
    
        public virtual RTP3_Centers RTP3_Centers { get; set; }
        public virtual RTP3_GUID RTP3_GUID { get; set; }
        public virtual RTP3_Unom RTP3_Unom { get; set; }
    }
}
